name: Deploy to Railway DEV Enviroment
  
on: 
  push:
    branches:
      - "develop"

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install packages
        run: npm install

      - name: Railway CLI
        run: npm install -g @railway/cli
      
      - name: Deploy to Railway
        run: railway up --service ${{ secrets.RAILWAY_SERVICES_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_DEVELOP_TOKEN }}