name: Deploy to Railway PROD Enviroment
  
on: 
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install packages
        run: npm install

      - name: Railway CLI
        run: npm install -g @railway/cli
      
      - name: Prisma Migrate
        run:  railway run --service ${{ secrets.RAILWAY_SERVICES_ID }} npx prisma migrate dev
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_PROD_TOKEN }}

      - name: Deploy to Railway
        run: railway up --service ${{ secrets.RAILWAY_SERVICES_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_PROD_TOKEN }}

      
        